### PR TITLE
Enable BR2_PACKAGE_LINUX_TOOLS_PERF in defconfig

### PR DESCRIPTION
**Pull request by glebm**
It helps to have a basic profiler installed by default

### CODE REVIEW

**Comment by pingflood** [comment]
In the RetroFW v2.0 buildroot version the BR2_PACKAGE_PERF and his derivatives (such as BR2_LINUX_KERNEL_TOOL_PERF) are deprecated (in Legacy config options) and have no effect.

**Comment by glebm** [comment]
@pingflood Is there another way to build `perf`?

**Comment by glebm** [comment]
Looks like it's `BR2_PACKAGE_LINUX_TOOLS_PERF` now:

https://github.com/retrofw/buildroot/blob/d45bc1d422ef5e3f50fe6973cd80dc075cfe1fc6/Config.in.legacy#L1005-L1011

**Comment by pingflood** [comment]
AFAIK, the BR2_PACKAGE_LINUX_TOOLS_PERF is for when the buildroot is building the kernel sources, which unfortunately isn't RetroFW case. :(

perf1
perf2
perf3

**Comment by glebm** [comment]
Ah, right. If you have access to the kernel source and it's unclear when it can be open-sourced, I'd appreciate if you could add a pre-built `perf` binary to the overlay.

There is a performance issue with DevilutionX that only appears on RetroFW and this will help us debug it

**Pull request closed without merging**
